<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Statistics\Form\StatisticsByValueForm $form
 * @var array $results
 * @var array $totals
 * @var string $type "value"
 * @var string[] $resourceTypes
 * @var int[]|null $periods
 * @var int[] $years
 * @var int $yearFilter
 * @var int $monthFilter
 * @var string $propertyFilter
 * @var string $valueTypeFilter
 * @var string $byPeriodFilter
 * @var string $compute
 * @var bool $hasAccess
 * @var bool $hasAdvancedSearch
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$urlHelper = $plugins->get('url');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()->prependStylesheet($assetUrl('css/statistics.css', 'Statistics'));

$this->htmlElement('body')->appendAttribute('class', 'statistics browse');

$isAdminRequest = $this->status()->isAdminRequest();
$query = $this->params()->fromQuery();

$currentUrl = $urlHelper(null, [], true);

$isMetadata = in_array($valueTypeFilter, ['resource_class', 'resource_template', 'owner']);
$isResource = $valueTypeFilter === 'resource';
$isUri = $valueTypeFilter === 'uri';
$isResourceClass = $valueTypeFilter === 'resource_class';
$isResourceTemplate = $valueTypeFilter === 'resource_template';
$isOwner = $valueTypeFilter === 'owner';
$isLinked = $isResource || $isResourceClass || $isResourceTemplate || $isOwner;

$isAllPeriods = $byPeriodFilter === 'all';
$isYearPeriods = $byPeriodFilter === 'year';
// $hasResults = !empty($results) && ($isAllPeriods ? !empty($results['all']) : true);

$submit = $form->get('submit');
$form->remove('submit');
$currentQuery = $this->params()->fromQuery();
$currentQueryNoSort = $currentQuery;
unset($currentQueryNoSort['sort_by']);

$form->prepare();
?>

<?= $this->pageTitle($translate('By value'), 1, $isAdminRequest ? $translate('Statistics') : null) ?>

<?= $this->partial('common/statistics-nav') ?>

<?= $this->form($form) ?>

<div id="page-actions">
    <?= $this->formButton($submit) ?>
</div>

<?php if (count($results) && ($propertyFilter || $isMetadata) && !is_null($periods)): ?>

<div class="browse-controls">
    <?php //= $this->pagination() ?>
    <div class="statistics-export">
        <?= $hyperlink($translate('ODS'), $urlHelper('admin/statistics/default/output', ['output' => 'ods'], ['query' => $query], true)) ?>
        <?= $hyperlink($translate('TSV'), $urlHelper('admin/statistics/default/output', ['output' => 'tsv'], ['query' => $query], true)) ?>
        <?= $hyperlink($translate('CSV'), $urlHelper('admin/statistics/default/output', ['output' => 'csv'], ['query' => $query], true)) ?>
    </div>
</div>

<?php endif; ?>

<?php if (!$propertyFilter && !$isMetadata): ?>

<p><?= $translate('Select a metadata to get statistics on it.') ?></p>

<?php elseif (is_null($periods)): ?>

<p><?= $translate('Check the form.') ?></p>

<?php elseif ($isAllPeriods && count($results)): ?>
<?php $period = 'all'; ?>

<table class="tablesaw statistics-table" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <a href="<?= $escapeAttr($currentUrl . '?' . http_build_query($currentQueryNoSort + ['sort_by' => 'value'], '', '&', PHP_QUERY_RFC3986)) ?>"><?= $translate('Value') ?></a>
            </th>
            <?php if ($isLinked): ?>
            <th>
                <span><?= $translate('Label') ?></span>
            </th>
            <?php endif; ?>
            <?php foreach ($resourceTypes  as $resourceType): ?>
            <th>
                <span><?= $resourceType ?></span>
            </th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <tr class="statistics-stat">
            <td class="statistics-field statistics-totals"><?= $translate('Totals') ?></td>
            <?php if ($isLinked): ?>
            <td class="statistics-label statistics-totals"></td>
            <?php endif; ?>
            <?php foreach ($resourceTypes as $resourceType): ?>
            <td class="statistics-hits statistics-totals"><?= isset($totals[$period][$resourceType]) ? $totals[$period][$resourceType] : '' ?></td>
            <?php endforeach; ?>
        </tr>
<?php foreach ($results as $value => $result): ?>
        <tr class="statistics-stat">
            <td class="statistics-field"><?= $isUri ? '<a href="' . $escapeAttr($value) . '" target="_blank" rel="noopener">' . $escape($result['l']) . '</a>' : $escape($value) ?></td>
            <?php if ($isLinked): ?>
            <td class="statistics-label"><?= $escape($result['l']) ?></td>
            <?php endif; ?>
            <?php foreach ($resourceTypes as $resourceType): ?>
            <td class="statistics-hits"><?= isset($result['t'][$period][$resourceType]) ? $result['t'][$period][$resourceType] : '' ?></td>
            <?php endforeach; ?>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php elseif (!$isAllPeriods && count($results)): ?>

<table class="tablesaw statistics-table" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <a href="<?= $escapeAttr($currentUrl . '?' . http_build_query($currentQueryNoSort + ['sort_by' => 'value'], '', '&', PHP_QUERY_RFC3986)) ?>"><?= $translate('Value') ?></a>
            </th>
            <?php if ($isLinked): ?>
            <th>
                <span><?= $translate('Label') ?></span>
            </th>
            <?php endif; ?>
            <?php foreach (array_keys($periods) as $period): ?>
            <th>
                <span><?= $isYearPeriods ? $period : sprintf('%04d %02d', substr((string) $period, 0, 4), substr((string) $period, 4, 2)) ?></span>
            </th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <tr class="statistics-stat">
            <td class="statistics-field statistics-totals"><?= $translate('Totals') ?></td>
            <?php if ($isLinked): ?>
            <td class="statistics-label statistics-totals"></td>
            <?php endif; ?>
            <?php foreach (array_keys($periods) as $period): ?>
            <td class="statistics-hits statistics-totals"><?php
                // There may be missing resource types.
                $t = isset($totals[$period]) ? array_replace(array_fill_keys($resourceTypes, null), $totals[$period]) : array_fill_keys($resourceTypes, null);
                echo implode(' / ', $t);
            ?></td>
            <?php endforeach; ?>
        </tr>
<?php foreach ($results as $value => $result): ?>
        <tr class="statistics-stat">
            <td class="statistics-field"><?= $isUri ? '<a href="' . $escapeAttr($value) . '" target="_blank" rel="noopener">' . $escape($result['l']) . '</a>' : $escape($value) ?></td>
            <?php if ($isLinked): ?>
            <td class="statistics-label"><?= $escape($result['l']) ?></td>
            <?php endif; ?>
            <?php foreach (array_keys($periods) as $period): ?>
            <td class="statistics-hits"><?php
                // There may be missing resource types.
                $t = isset($result['t'][$period]) ? array_replace(array_fill_keys($resourceTypes, null), $result['t'][$period]) : array_fill_keys($resourceTypes, null);
                echo implode(' / ', $t);
            ?></td>
            <?php endforeach; ?>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>

    <br class="clear" />
    <?php $totalResources = $plugins->get('apiResourcesTotalResults')(); ?>
    <?php if (!$totalResources): ?>
        <h2><?= $translate('There is no resources yet.') ?></h2>
    <?php else: ?>
        <p><?= sprintf($translate('The query searched %s resources and returned no results.'), $totalResources) ?></p>
        <p><a href="<?= $urlHelper('admin/statistics/default', ['action' => 'by-value'], true) ?>"><?= $translate('See all statistics.') ?></a></p>
    <?php endif; ?>

<?php endif; ?>
