<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var bool $hasDependencies
 * @var bool $hasReadOnly
 * @var bool $hasFullAccess
 * @var bool $hasFakeReadOnly
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->htmlElement('body');
echo $this->pageTitle($this->translate('Adminer database manager'));
?>

<strong><?= $translate('WARNING') ?></strong>
<p><?= $translate('Use it at your own risk.') ?></p>
<p><?= $translate('It is highly recommended to use a read-only user to access database, because it’s very easy to break a database, even for people who know the Omeka code and all the modules perfectly.') ?></p>
<p><?= $translate('In all cases, it’s always recommended to backup your files and your databases automatically and before risky and non-risky commands, and to check your archives regularly, so you can roll back if needed.') ?></p>
<p><?= $escape($translate('To edit an element, use the key <control> + click.')) ?></p>
<p><?= $translate('Besides, some designs are not adapted for the interface for editor. They can be selected with the button in the bottom right.') ?></p>
<p><?= $translate('Warning: currently, the language and the design cannot be changed on the first page of Adminer.') ?></p>
<p>
<?php
if ($hasDependencies && ($hasReadOnly || $hasFullAccess)):
    if (!$hasFakeReadOnly) {
        echo $hyperlink($translate('Read-only access (interface for editor)'), $url('admin/adminer-editor-mysql', [], ['query' => ['login' => 'readonly']]), ['target' => '_blank']);
        echo '<br/>';
        echo $hyperlink($translate('Read-only access'), $url('admin/adminer-mysql', [], ['query' => ['login' => 'readonly']]), ['target' => '_blank']);
        echo '<br/>';
    }
    if ($hasFullAccess):
        echo $hyperlink($translate('Full access (interface for editor)'), $url('admin/adminer-editor-mysql', [], ['query' => ['login' => 'full']]), ['target' => '_blank']);
        echo '<br/>';
        echo $hyperlink($translate('Full access'), $url('admin/adminer-mysql', [], ['query' => ['login' => 'full']]), ['target' => '_blank']);
    else:
        echo $translate('Full-access user is not defined.');
    endif;
else:
    echo $translate('Read-only user is not defined.');
endif;
?>
</p>
