<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $query
 */

$translate = $this->plugin('translate');
?>

<?php
$element = new \Laminas\Form\Element\Radio('is_dynamic');
$element
    ->setLabel('Is dynamic item set') // @translate
    ->setLabelAttributes(['class' => 'type-radio'])
    ->setValueOptions([
        '1' => 'Is dynamic', // @translate
        '0' => 'Is not dynamic', // @translate
        // Should be last because of "0".
        '' => 'Any', // @translate
    ])
    ->setValue($query['is_dynamic'] ?? '')
    ->setAttributes([
        'id' => 'is_dynamic',
        'class' => 'query-is-dynamic',
        'value' => $query['is_dynamic'] ?? '',
        'aria-label' => $translate('Search dynamic item sets'), // @translate
    ]);
echo $this->formRow($element);
