<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageRepresentation $page
 */

$layouts = [];
$blockLayout = $this->blockLayout();
foreach ($page->blocks() as $block) {
    if (!array_key_exists($block->layout(), $layouts)) {
        // Prepare render only once per layout type.
        $layouts[$block->layout()] = null;
        $blockLayout->prepareRender($block->layout());
    }
    echo $blockLayout->render($block);
}
