<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Statistics\Form\AnalyticsByDownloadForm|\Statistics\Form\AnalyticsByResourceForm $form
 * @var \Statistics\Api\Representation\StatRepresentation[] $resources
 * @var \Statistics\Api\Representation\StatRepresentation[] $stats
 * @var string $userStatus
 * @var string $type
 * @var array $columns
 */

include __DIR__ . '/../../site/analytics/by-stat.phtml';
