<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Statistics\Form\AnalyticsByFieldForm $form
 * @var array $results
 * @var string $type "field"
 * @var string $field
 * @var string $labelField
 * @var string $totalHits
 * @var string $totalNotEmpty
 * @var string $userStatus
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$analytics = $plugins->get('analytics');
$urlHelper = $plugins->get('url');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()->prependStylesheet($assetUrl('css/statistics.css', 'Statistics'));

$this->htmlElement('body')->appendAttribute('class', 'statistics browse');

$isAdminRequest = $this->status()->isAdminRequest();

$totalResults = $this->pagination()->getPaginator()->getTotalCount();
$currentUrl = $urlHelper(null, [], true);
$currentQuery = $this->params()->fromQuery();
$currentQueryNoSort = $currentQuery;
unset($currentQueryNoSort['sort_by']);

$submit = $form->get('submit');
$form->remove('submit');

$form->prepare();
?>

<?= $this->pageTitle(sprintf($translate('Analytics (%s total)'), $totalResults), 1, $isAdminRequest ? $translate('Analytics') : null) ?>

<?= $this->partial('common/analytics-nav') ?>

<?= $this->form($form) ?>

<div id="page-actions">
    <?= $this->formButton($submit) ?>
</div>

<p>
    <strong><?= sprintf($translate('By %s (%s)'), $labelField, $analytics->humanUserStatus($userStatus)) ?></strong>
    <em><?= sprintf($translate('[%d filled values / %d total hits]'), $totalNotEmpty, $totalHits) ?></em>
</p>

<?php if ($totalResults): ?>

<div class="browse-controls">
    <?= $pagination = $this->pagination() ?>
    <?php //= $this->sortSelector($sortHeadings) ?>
</div>

<table class="tablesaw statistics-table" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <a href="<?= $escapeAttr($currentUrl . '?' . http_build_query($currentQueryNoSort + ['sort_by' => $field], '', '&', PHP_QUERY_RFC3986)) ?>"><?= $labelField ?></a>
            </th>
            <th>
                <a href="<?= $escapeAttr($currentUrl . '?' . http_build_query($currentQueryNoSort + ['sort_by' => 'hits'], '', '&', PHP_QUERY_RFC3986)) ?>"><?= $translate('Hits') ?></a>
            </th>
            <th>
                <a href="<?= $escapeAttr($currentUrl . '?' . http_build_query($currentQueryNoSort + ['sort_by' => 'hits'], '', '&', PHP_QUERY_RFC3986)) ?>"><?= $translate('Percent') ?></a>
            </th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($results as /* $position => */ $result): ?>
        <tr class="statistics-stat">
            <td class="statistics-field"><?= $result[$field] ?></td>
            <td class="statistics-hits"><?= $result['hits'] ?></td>
            <td class="statistics-percent"><?= round($result['hits'] * 100 / $totalNotEmpty, 1) ?>%</td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?= $pagination ?>

<?php else: ?>

<div class="browse-controls">
</div>

<br class="clear" />
<div class="no-resources">
<?php if (!$totalHits): ?>
    <p><?= $translate('There is no hit yet.') ?></p>
<?php else: ?>
    <p><?= sprintf($translate('The query searched %s hits and returned no results.'), $totalHits) ?></p>
    <p><a href="<?= $urlHelper('admin/analytics/default', ['action' => 'by-' . $type], true) ?>"><?= $translate('See all analytics.') ?></a></p>
<?php endif; ?>
</div>

<?php endif; ?>
