<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Statistics\Form\AnalyticsByValueForm $form
 * @var array $results
 * @var string $type "value"
 * @var array $hits
 * @var int[]|null $periods
 * @var int[] $years
 * @var int $yearFilter
 * @var int $monthFilter
 * @var string $propertyFilter
 * @var string $valueTypeFilter
 * @var string $byPeriodFilter
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$urlHelper = $plugins->get('url');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()->prependStylesheet($assetUrl('css/statistics.css', 'Statistics'));

$this->htmlElement('body')->appendAttribute('class', 'statistics browse');

$isAdminRequest = $this->status()->isAdminRequest();

$currentUrl = $urlHelper(null, [], true);
$currentQuery = $this->params()->fromQuery();
$currentQueryNoSort = $currentQuery;
unset($currentQueryNoSort['sort_by']);

$isSimpleValue = !in_array($valueTypeFilter, ['resource', 'uri']);
$isResource = $valueTypeFilter === 'resource';
$isUri = $valueTypeFilter === 'uri';
$isByAll = !in_array($byPeriodFilter, ['year', 'month']);

$isAllPeriods = $byPeriodFilter === 'all';
$isYearPeriods = $byPeriodFilter === 'year';
// $hasResults = !empty($results) && ($isAllPeriods ? !empty($results['all']) : true);

$submit = $form->get('submit');
$form->remove('submit');

$form->prepare();
?>

<?= $this->pageTitle($translate('By value'), 1, $isAdminRequest ? $translate('Analytics') : null) ?>

<?= $this->partial('common/analytics-nav') ?>

<?= $this->form($form) ?>

<div id="page-actions">
    <?= $this->formButton($submit) ?>
</div>

<?php if (!$propertyFilter): ?>

<p><?= $translate('Select a property to get analytics on it.') ?></p>

<?php elseif (is_null($periods)): ?>

<p><?= $translate('Check the form.') ?></p>

<?php elseif ($isAllPeriods && count($results)): ?>

<table class="tablesaw statistics-table" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <a href="<?= $currentUrl . '?sort_by=value' ?>"><?= $translate('Value') ?></a>
            </th>
            <?php if ($isResource): ?>
            <th>
                <span><?= $translate('Label') ?></span>
            </th>
            <?php endif; ?>
            <th>
                <a href="<?= $escapeAttr($currentUrl . '?' . http_build_query($currentQueryNoSort + ['sort_by' => 'hits'], '', '&', PHP_QUERY_RFC3986)) ?>"><?= $translate('Hits') ?></a>
            </th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($results as /* $position => */ $result): ?>
        <tr class="statistics-stat">
            <td class="statistics-field"><?= $isUri ? '<a href="' . $escapeAttr($result['value']) . '" target="_blank" rel="noopener">' . $escape($result['label']) . '</a>' : $escape($result['value']) ?></td>
            <?php if ($isResource): ?>
            <td class="statistics-label"><?= $escape($result['label']) ?></td>
            <?php endif; ?>
            <td class="statistics-hits"><?= $result['hits'] ?></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php elseif (!$isAllPeriods && count($results)): ?>

<table class="tablesaw statistics-table" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <a href="<?= $escapeAttr($currentUrl . '?' . http_build_query($currentQueryNoSort + ['sort_by' => 'value'], '', '&', PHP_QUERY_RFC3986)) ?>"><?= $translate('Value') ?></a>
            </th>
            <?php if ($isResource): ?>
            <th>
                <span><?= $translate('Label') ?></span>
            </th>
            <?php endif; ?>
            <?php foreach (array_keys($periods) as $period): ?>
            <th>
                <span><?= $isYearPeriods ? $period : sprintf('%04d %02d', substr($period, 0, 4), substr($period, 4, 2)) ?></span>
            </th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
<?php foreach ($results as $value => $result): ?>
        <tr class="statistics-stat">
            <td class="statistics-field"><?= $isUri ? '<a href="' . $escapeAttr($value) . '" target="_blank" rel="noopener">' . $escape($result['label']) . '</a>' : $escape($value) ?></td>
            <?php if ($isResource): ?>
            <td class="statistics-label"><?= $escape($result['label']) ?></td>
            <?php endif; ?>
            <?php foreach (array_keys($periods) as $period): ?>
            <td class="statistics-hits"><?= $result['hits'][$period] ?? '' ?></td>
            <?php endforeach; ?>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>

    <br class="clear" />
    <?php $totalHits = $this->api()->search('hits', ['limit' => 0])->getTotalResults(); ?>
    <?php if (!$totalHits): ?>
        <h2><?= $translate('There is no hit yet.') ?></h2>
    <?php else: ?>
        <p><?= sprintf($translate('The query searched %s hits and returned no results.'), $totalHits) ?></p>
        <p><a href="<?= $urlHelper('admin/analytics/default', ['action' => 'by-value'], true) ?>"><?= $translate('See all analytics.') ?></a></p>
    <?php endif; ?>

<?php endif; ?>
